export const GENEROS = [
  'RPG',
  'Acción',
  'Aventura',
  'Shooter',
  'Terror',
  'Estrategia',
  'Simulación',
  'Deportes',
  'Carreras',
  'Indie',
  'Plataformas',
  'Supervivencia',
] as const;

export const PLATAFORMAS = [
  'PC',
  'PlayStation 4',
  'PlayStation 5',
  'Xbox One',
  'Xbox Series',
  'Nintendo Switch',
] as const;

export const CARACTERISTICAS = [
  'Mundo abierto',
  'Un jugador',
  'Multijugador',
  'Cooperativo',
  'Historia',
  'Exploración',
  'Combate desafiante',
  'Construcción',
  'Supervivencia',
  'Competitivo',
  'Gestión',
  'Estrategia por turnos',
  'Terror',
  'Roguelike',
  'Sandbox',
] as const;

export interface JuegoSeed {
  titulo: string;
  descripcion: string;
  generos: (typeof GENEROS)[number][];
  plataformas: (typeof PLATAFORMAS)[number][];
  caracteristicas: (typeof CARACTERISTICAS)[number][];
}

const pcConsolas: JuegoSeed['plataformas'] = [
  'PC',
  'PlayStation 4',
  'PlayStation 5',
  'Xbox One',
  'Xbox Series',
];
const pcAnterior: JuegoSeed['plataformas'] = [
  'PC',
  'PlayStation 4',
  'Xbox One',
];
const pcActual: JuegoSeed['plataformas'] = [
  'PC',
  'PlayStation 5',
  'Xbox Series',
];
const todas: JuegoSeed['plataformas'] = [...pcConsolas, 'Nintendo Switch'];

function juego(
  titulo: string,
  descripcion: string,
  generos: JuegoSeed['generos'],
  plataformas: JuegoSeed['plataformas'],
  caracteristicas: JuegoSeed['caracteristicas'],
): JuegoSeed {
  return {
    titulo,
    descripcion,
    generos,
    plataformas: [...plataformas],
    caracteristicas,
  };
}

// Plataformas con versiones publicadas; no se enumeran por retrocompatibilidad.
// Los títulos ambiguos indican la edición elegida. Fechas e imágenes se omiten
// para no sobrescribir metadatos existentes con información aproximada.
export const CATALOGO: JuegoSeed[] = [
  juego(
    'Elden Ring',
    'RPG de acción con exploración libre y combates exigentes en las Tierras Intermedias.',
    ['RPG', 'Acción'],
    pcConsolas,
    [
      'Mundo abierto',
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Combate desafiante',
    ],
  ),
  juego(
    'The Witcher 3',
    'Aventura de rol protagonizada por Geralt, con decisiones narrativas y cacería de monstruos.',
    ['RPG', 'Aventura'],
    todas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Dark Souls III',
    'RPG de acción en un mundo oscuro con jefes y combate exigente.',
    ['RPG', 'Acción'],
    pcAnterior,
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Combate desafiante',
    ],
  ),
  juego(
    'Sekiro: Shadows Die Twice',
    'Aventura de acción centrada en el sigilo y los duelos de espadas.',
    ['Acción', 'Aventura'],
    pcAnterior,
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Cyberpunk 2077',
    'RPG de acción con decisiones narrativas en la ciudad futurista de Night City.',
    ['RPG', 'Acción'],
    pcConsolas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    "Baldur's Gate 3",
    'Rol de fantasía con decisiones, compañeros y combates tácticos por turnos.',
    ['RPG', 'Estrategia'],
    pcActual,
    [
      'Un jugador',
      'Cooperativo',
      'Historia',
      'Exploración',
      'Estrategia por turnos',
    ],
  ),
  juego(
    'Divinity: Original Sin 2',
    'RPG de fantasía con interacción entre elementos y combate por turnos.',
    ['RPG', 'Estrategia'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    [
      'Un jugador',
      'Cooperativo',
      'Historia',
      'Exploración',
      'Estrategia por turnos',
    ],
  ),
  juego(
    'The Elder Scrolls V: Skyrim',
    'RPG de exploración en una región de fantasía con dragones y numerosas misiones.',
    ['RPG', 'Aventura'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Fallout 4',
    'RPG posapocalíptico con exploración, decisiones y construcción de asentamientos.',
    ['RPG', 'Shooter'],
    pcConsolas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración', 'Construcción'],
  ),
  juego(
    'Red Dead Redemption 2',
    'Aventura del oeste sobre una banda de forajidos y un mundo abierto detallado.',
    ['Acción', 'Aventura'],
    pcAnterior,
    ['Mundo abierto', 'Un jugador', 'Multijugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Grand Theft Auto V',
    'Acción en Los Santos con tres protagonistas y un modo multijugador en línea.',
    ['Acción', 'Aventura'],
    pcConsolas,
    ['Mundo abierto', 'Un jugador', 'Multijugador', 'Historia', 'Sandbox'],
  ),
  juego(
    'God of War',
    'Aventura de Kratos y Atreus en la mitología nórdica, edición de 2018.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'God of War Ragnarök',
    'Continuación de la aventura nórdica de Kratos y Atreus.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Horizon Zero Dawn',
    'Aventura de Aloy en un mundo abierto habitado por máquinas, edición original.',
    ['Acción', 'RPG'],
    ['PC', 'PlayStation 4'],
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Horizon Forbidden West',
    'Aloy explora nuevas regiones y combate máquinas en una aventura de mundo abierto.',
    ['Acción', 'RPG'],
    ['PC', 'PlayStation 4', 'PlayStation 5'],
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    "Assassin's Creed Odyssey",
    'Aventura de acción y rol ambientada en la antigua Grecia.',
    ['RPG', 'Acción', 'Aventura'],
    pcAnterior,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    "Assassin's Creed Valhalla",
    'Aventura vikinga con exploración y desarrollo de un asentamiento.',
    ['RPG', 'Acción', 'Aventura'],
    pcConsolas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Hogwarts Legacy',
    'RPG de acción y exploración ambientado en el mundo mágico de Hogwarts.',
    ['RPG', 'Aventura'],
    todas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Resident Evil 2',
    'Remake de 2019: supervivencia y terror en Raccoon City.',
    ['Terror', 'Supervivencia'],
    pcConsolas,
    ['Un jugador', 'Historia', 'Exploración', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Resident Evil 4',
    'Remake de 2023: rescate, acción y terror protagonizados por Leon Kennedy.',
    ['Acción', 'Terror', 'Shooter'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Resident Evil Village',
    'Aventura de terror y supervivencia en un pueblo aislado.',
    ['Terror', 'Supervivencia', 'Shooter'],
    pcConsolas,
    ['Un jugador', 'Historia', 'Exploración', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Silent Hill 2',
    'Remake de 2024: terror psicológico y exploración en Silent Hill.',
    ['Terror', 'Aventura'],
    ['PC', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Exploración', 'Terror'],
  ),
  juego(
    'DOOM Eternal',
    'Shooter de acción rápida con gestión de recursos durante el combate.',
    ['Shooter', 'Acción'],
    todas,
    ['Un jugador', 'Multijugador', 'Combate desafiante'],
  ),
  juego(
    'DOOM',
    'Edición de 2016: shooter de acción contra demonios en instalaciones de Marte.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Combate desafiante'],
  ),
  juego(
    'Halo Infinite',
    'Shooter de ciencia ficción con campaña y partidas multijugador competitivas.',
    ['Shooter', 'Acción'],
    ['PC', 'Xbox One', 'Xbox Series'],
    [
      'Mundo abierto',
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Competitivo',
    ],
  ),
  juego(
    'Counter-Strike 2',
    'Shooter táctico competitivo por equipos con objetivos y economía por ronda.',
    ['Shooter'],
    ['PC'],
    ['Multijugador', 'Competitivo'],
  ),
  juego(
    'Valorant',
    'Shooter táctico por equipos que combina precisión y habilidades de agentes.',
    ['Shooter'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Multijugador', 'Competitivo'],
  ),
  juego(
    'Overwatch 2',
    'Shooter por equipos con héroes de distintos roles y objetivos compartidos.',
    ['Shooter', 'Acción'],
    todas,
    ['Multijugador', 'Competitivo'],
  ),
  juego(
    'Apex Legends',
    'Battle royale por escuadrones con personajes y habilidades diferenciadas.',
    ['Shooter', 'Acción'],
    todas,
    ['Multijugador', 'Competitivo'],
  ),
  juego(
    'Fortnite',
    'Battle royale con combate, construcción y modos creativos.',
    ['Shooter', 'Acción'],
    todas,
    ['Multijugador', 'Competitivo', 'Construcción', 'Sandbox'],
  ),
  juego(
    'Minecraft',
    'Sandbox de bloques con construcción, exploración y supervivencia.',
    ['Supervivencia', 'Aventura'],
    todas,
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Construcción',
      'Supervivencia',
      'Sandbox',
    ],
  ),
  juego(
    'Terraria',
    'Sandbox en dos dimensiones con exploración, construcción y combates.',
    ['Indie', 'Supervivencia', 'Aventura'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Construcción',
      'Supervivencia',
      'Sandbox',
    ],
  ),
  juego(
    'Stardew Valley',
    'Simulación de granja con vida comunitaria, cultivo y exploración.',
    ['Indie', 'Simulación', 'RPG'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Cooperativo', 'Gestión', 'Exploración'],
  ),
  juego(
    'Hades',
    'Roguelike de acción sobre intentos de escapar del inframundo griego.',
    ['Indie', 'Acción', 'RPG'],
    todas,
    ['Un jugador', 'Historia', 'Combate desafiante', 'Roguelike'],
  ),
  juego(
    'Hollow Knight',
    'Aventura de exploración y plataformas en un reino subterráneo.',
    ['Indie', 'Acción', 'Plataformas'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Celeste',
    'Plataformas de precisión sobre una escalada y la superación personal.',
    ['Indie', 'Plataformas'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'Cuphead',
    'Acción y plataformas con jefes exigentes y estética de animación clásica.',
    ['Indie', 'Acción', 'Plataformas'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Cooperativo', 'Combate desafiante'],
  ),
  juego(
    'Dead Cells',
    'Roguelike de acción y plataformas con rutas y equipo variables.',
    ['Indie', 'Acción', 'Plataformas'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Exploración', 'Combate desafiante', 'Roguelike'],
  ),
  juego(
    'Civilization VI',
    'Estrategia por turnos para desarrollar una civilización a través de las eras.',
    ['Estrategia'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Gestión', 'Estrategia por turnos'],
  ),
  juego(
    'Age of Empires IV',
    'Estrategia en tiempo real con civilizaciones históricas y gestión de recursos.',
    ['Estrategia'],
    ['PC', 'Xbox One', 'Xbox Series'],
    ['Un jugador', 'Multijugador', 'Competitivo', 'Gestión', 'Construcción'],
  ),
  juego(
    'Cities: Skylines',
    'Simulación de planificación urbana, servicios y transporte.',
    ['Simulación', 'Estrategia'],
    todas,
    ['Un jugador', 'Gestión', 'Construcción', 'Sandbox'],
  ),
  juego(
    'The Sims 4',
    'Simulación de vida con creación de hogares y relaciones entre personajes.',
    ['Simulación'],
    pcAnterior,
    ['Un jugador', 'Gestión', 'Construcción', 'Sandbox'],
  ),
  juego(
    'Forza Horizon 5',
    'Carreras en un mundo abierto inspirado en México.',
    ['Carreras'],
    ['PC', 'PlayStation 5', 'Xbox One', 'Xbox Series'],
    [
      'Mundo abierto',
      'Un jugador',
      'Multijugador',
      'Competitivo',
      'Exploración',
    ],
  ),
  juego(
    'Gran Turismo 7',
    'Carreras con colección de vehículos y competiciones en circuitos.',
    ['Carreras', 'Simulación'],
    ['PlayStation 4', 'PlayStation 5'],
    ['Un jugador', 'Multijugador', 'Competitivo'],
  ),
  juego(
    'EA Sports FC 24',
    'Fútbol con clubes, selecciones y modalidades individuales y competitivas.',
    ['Deportes', 'Simulación'],
    todas,
    ['Un jugador', 'Multijugador', 'Competitivo', 'Gestión'],
  ),
  juego(
    'Rocket League',
    'Partidos de fútbol con vehículos y juego competitivo por equipos.',
    ['Deportes', 'Carreras'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Competitivo'],
  ),
  juego(
    'Portal 2',
    'Aventura de puzles con portales, narrativa y campaña cooperativa.',
    ['Aventura'],
    ['PC'],
    ['Un jugador', 'Cooperativo', 'Historia'],
  ),
  juego(
    'It Takes Two',
    'Aventura diseñada para dos jugadores con mecánicas cooperativas variadas.',
    ['Aventura', 'Plataformas'],
    todas,
    ['Multijugador', 'Cooperativo', 'Historia'],
  ),
  juego(
    'Monster Hunter: World',
    'RPG de acción centrado en cacerías, equipo y cooperación.',
    ['RPG', 'Acción'],
    pcAnterior,
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Combate desafiante',
    ],
  ),
  juego(
    'Death Stranding',
    'Edición original: aventura de entregas y conexión entre comunidades aisladas.',
    ['Aventura', 'Acción'],
    ['PC', 'PlayStation 4'],
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
];
