export const GENEROS = [
  'RPG',
  'Acción',
  'Aventura',
  'Shooter',
  'Terror',
  'Estrategia',
  'Simulación',
  'Deportes',
  'Carreras',
  'Indie',
  'Plataformas',
  'Supervivencia',
  'Lucha',
] as const;

export const PLATAFORMAS = [
  'PC',
  'PlayStation 4',
  'PlayStation 5',
  'Xbox One',
  'Xbox Series',
  'Nintendo Switch',
] as const;

export const CARACTERISTICAS = [
  'Mundo abierto',
  'Un jugador',
  'Multijugador',
  'Cooperativo',
  'Historia',
  'Exploración',
  'Combate desafiante',
  'Construcción',
  'Supervivencia',
  'Competitivo',
  'Gestión',
  'Estrategia por turnos',
  'Terror',
  'Roguelike',
  'Sandbox',
] as const;

export interface JuegoSeed {
  titulo: string;
  descripcion: string;
  urlImagen?: string;
  generos: (typeof GENEROS)[number][];
  plataformas: (typeof PLATAFORMAS)[number][];
  caracteristicas: (typeof CARACTERISTICAS)[number][];
}

const pcConsolas: JuegoSeed['plataformas'] = [
  'PC',
  'PlayStation 4',
  'PlayStation 5',
  'Xbox One',
  'Xbox Series',
];
const pcAnterior: JuegoSeed['plataformas'] = [
  'PC',
  'PlayStation 4',
  'Xbox One',
];
const pcActual: JuegoSeed['plataformas'] = [
  'PC',
  'PlayStation 5',
  'Xbox Series',
];
const todas: JuegoSeed['plataformas'] = [...pcConsolas, 'Nintendo Switch'];

// App IDs revisados; las portadas se resuelven sin consultas externas.
const STEAM_APP_IDS: Readonly<Record<string, number>> = {
  'Elden Ring': 1245620,
  'The Witcher 3': 292030,
  'Dark Souls III': 374320,
  'Sekiro: Shadows Die Twice': 814380,
  'Cyberpunk 2077': 1091500,
  "Baldur's Gate 3": 1086940,
  'Divinity: Original Sin 2': 435150,
  'The Elder Scrolls V: Skyrim': 489830,
  'Fallout 4': 377160,
  'Red Dead Redemption 2': 1174180,
  'Grand Theft Auto V': 271590,
  'God of War': 1593500,
  'God of War Ragnarök': 2322010,
  'Horizon Zero Dawn': 1151640,
  'Horizon Forbidden West': 2420110,
  "Assassin's Creed Odyssey": 812140,
  "Assassin's Creed Valhalla": 2208920,
  'Hogwarts Legacy': 990080,
  'Resident Evil 2': 883710,
  'Resident Evil 4': 2050650,
  'Resident Evil Village': 1196590,
  'Silent Hill 2': 2124490,
  'DOOM Eternal': 782330,
  DOOM: 379720,
  'Halo Infinite': 1240440,
  'Counter-Strike 2': 730,
  'Overwatch 2': 2357570,
  'Apex Legends': 1172470,
  Terraria: 105600,
  'Stardew Valley': 413150,
  Hades: 1145360,
  'Hollow Knight': 367520,
  Celeste: 504230,
  Cuphead: 268910,
  'Dead Cells': 588650,
  'Civilization VI': 289070,
  'Age of Empires IV': 1466860,
  'Cities: Skylines': 255710,
  'The Sims 4': 1222670,
  'Forza Horizon 5': 1551360,
  'EA Sports FC 24': 2195250,
  'Rocket League': 252950,
  'Portal 2': 620,
  'It Takes Two': 1426210,
  'Monster Hunter: World': 582010,
  'Death Stranding': 1190460,
  "Marvel's Spider-Man Remastered": 1817070,
  "Marvel's Spider-Man: Miles Morales": 1817190,
  "Marvel's Spider-Man 2": 2651280,
  'Far Cry 2': 19900,
  'Far Cry 3': 220240,
  'Far Cry 4': 298110,
  'Far Cry 5': 552520,
  'Far Cry Primal': 371660,
  'Devil May Cry 5': 601150,
  'Ori and the Blind Forest: Definitive Edition': 387290,
  'Ori and the Will of the Wisps': 1057090,
  'Final Fantasy VII Remake Intergrade': 1462040,
  'Final Fantasy VII Rebirth': 2909400,
  'Final Fantasy XVI': 2515020,
  'Mortal Kombat 11': 976310,
  'Mortal Kombat 1': 1971870,
  'The Binding of Isaac: Rebirth': 250900,
  'DAVE THE DIVER': 1868140,
  'Until Dawn': 2172010,
  'Lies of P': 1627720,
  Undertale: 391540,
  Sifu: 2138710,
  'NINJA GAIDEN 2 Black': 3287520,
  'NINJA GAIDEN 4': 2627260,
  Megabonk: 3405340,
  "No Man's Sky": 275850,
  'Sniper Elite 5': 1029690,
  'Mortal Shell': 1110910,
  'Batman: Arkham Asylum': 35140,
  'Batman: Arkham City': 200260,
  'Batman: Arkham Knight': 208650,
  'BioShock Remastered': 409710,
  'BioShock Infinite': 8870,
  Blasphemous: 774361,
  'Blasphemous 2': 2114740,
  'Borderlands 2': 49520,
  'Borderlands 3': 397540,
  'Borderlands 4': 1285190,
  'Clair Obscur: Expedition 33': 1903340,
  'Crash Bandicoot N. Sane Trilogy': 731490,
  "Crash Bandicoot 4: It's About Time": 1378990,
  'Ratchet & Clank: Rift Apart': 1895880,
  'Diablo IV': 2344520,
  'Detroit: Become Human': 1222140,
  'Left 4 Dead 2': 550,
  'Little Nightmares': 424840,
  'Little Nightmares II': 860510,
  'Little Nightmares III': 1392860,
  'Metal Gear Rising: Revengeance': 235460,
  'Middle-earth: Shadow of Mordor': 241930,
  'Middle-earth: Shadow of War': 356190,
  'Star Wars Jedi: Fallen Order': 1172380,
  'Star Wars Jedi: Survivor': 1774580,
  'Street Fighter 6': 1364780,
  ULTRAKILL: 1229490,
  'Tomb Raider (2013)': 203160,
  'Rise of the Tomb Raider': 391220,
  'Shadow of the Tomb Raider': 750920,
  "Tom Clancy's Ghost Recon Wildlands": 460930,
  "Tom Clancy's Ghost Recon Breakpoint": 2231380,
  'The Last of Us Part I': 1888930,
  'The Last of Us Part II Remastered': 2531310,
  'Grand Theft Auto IV': 12210,
  'Dead by Daylight': 381210,
  'Marvel Rivals': 2767030,
  'Battlefield 1': 1238840,
  'Battlefield 6': 2807960,
  'Call of Duty: Modern Warfare (2019)': 2000950,
  'ARK: Survival Ascended': 2399830,
  'Split Fiction': 2001120,
  Subnautica: 264710,
  'Subnautica: Below Zero': 848450,
  'Black Myth: Wukong': 2358720,
  Stray: 1332010,
  'Tekken 8': 1778820,
  'PAYDAY 2': 218620,
  'Metal Gear Solid V: The Phantom Pain': 287700,
  'Metal Gear Solid Delta: Snake Eater': 2417610,
  'Guilty Gear -Strive-': 1384160,
  'Disco Elysium - The Final Cut': 632470,
  'Halo: The Master Chief Collection': 976730,
};

const PORTADAS: Readonly<Record<string, string>> = Object.fromEntries(
  Object.entries(STEAM_APP_IDS).map(([titulo, appId]) => [
    titulo,
    `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`,
  ]),
);

function juego(
  titulo: string,
  descripcion: string,
  generos: JuegoSeed['generos'],
  plataformas: JuegoSeed['plataformas'],
  caracteristicas: JuegoSeed['caracteristicas'],
  urlImagen: string | undefined = PORTADAS[titulo],
): JuegoSeed {
  return {
    titulo,
    descripcion,
    urlImagen,
    generos,
    plataformas: [...plataformas],
    caracteristicas,
  };
}

// Plataformas con versiones publicadas; no se enumeran por retrocompatibilidad.
// Los títulos ambiguos indican la edición elegida. Las fechas se omiten
// para no incorporar información aproximada.
export const CATALOGO: JuegoSeed[] = [
  juego(
    'Elden Ring',
    'RPG de acción con exploración libre y combates exigentes en las Tierras Intermedias.',
    ['RPG', 'Acción'],
    pcConsolas,
    [
      'Mundo abierto',
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Combate desafiante',
    ],
  ),
  juego(
    'The Witcher 3',
    'Aventura de rol protagonizada por Geralt, con decisiones narrativas y cacería de monstruos.',
    ['RPG', 'Aventura'],
    todas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Dark Souls III',
    'RPG de acción en un mundo oscuro con jefes y combate exigente.',
    ['RPG', 'Acción'],
    pcAnterior,
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Combate desafiante',
    ],
  ),
  juego(
    'Sekiro: Shadows Die Twice',
    'Aventura de acción centrada en el sigilo y los duelos de espadas.',
    ['Acción', 'Aventura'],
    pcAnterior,
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Cyberpunk 2077',
    'RPG de acción con decisiones narrativas en la ciudad futurista de Night City.',
    ['RPG', 'Acción'],
    pcConsolas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    "Baldur's Gate 3",
    'Rol de fantasía con decisiones, compañeros y combates tácticos por turnos.',
    ['RPG', 'Estrategia'],
    pcActual,
    [
      'Un jugador',
      'Cooperativo',
      'Historia',
      'Exploración',
      'Estrategia por turnos',
    ],
  ),
  juego(
    'Divinity: Original Sin 2',
    'RPG de fantasía con interacción entre elementos y combate por turnos.',
    ['RPG', 'Estrategia'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    [
      'Un jugador',
      'Cooperativo',
      'Historia',
      'Exploración',
      'Estrategia por turnos',
    ],
  ),
  juego(
    'The Elder Scrolls V: Skyrim',
    'RPG de exploración en una región de fantasía con dragones y numerosas misiones.',
    ['RPG', 'Aventura'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Fallout 4',
    'RPG posapocalíptico con exploración, decisiones y construcción de asentamientos.',
    ['RPG', 'Shooter'],
    pcConsolas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración', 'Construcción'],
  ),
  juego(
    'Red Dead Redemption 2',
    'Aventura del oeste sobre una banda de forajidos y un mundo abierto detallado.',
    ['Acción', 'Aventura'],
    pcAnterior,
    ['Mundo abierto', 'Un jugador', 'Multijugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Grand Theft Auto V',
    'Acción en Los Santos con tres protagonistas y un modo multijugador en línea.',
    ['Acción', 'Aventura'],
    pcConsolas,
    ['Mundo abierto', 'Un jugador', 'Multijugador', 'Historia', 'Sandbox'],
  ),
  juego(
    'God of War',
    'Aventura de Kratos y Atreus en la mitología nórdica, edición de 2018.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'God of War Ragnarök',
    'Continuación de la aventura nórdica de Kratos y Atreus.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Horizon Zero Dawn',
    'Aventura de Aloy en un mundo abierto habitado por máquinas, edición original.',
    ['Acción', 'RPG'],
    ['PC', 'PlayStation 4'],
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Horizon Forbidden West',
    'Aloy explora nuevas regiones y combate máquinas en una aventura de mundo abierto.',
    ['Acción', 'RPG'],
    ['PC', 'PlayStation 4', 'PlayStation 5'],
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    "Assassin's Creed Odyssey",
    'Aventura de acción y rol ambientada en la antigua Grecia.',
    ['RPG', 'Acción', 'Aventura'],
    pcAnterior,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    "Assassin's Creed Valhalla",
    'Aventura vikinga con exploración y desarrollo de un asentamiento.',
    ['RPG', 'Acción', 'Aventura'],
    pcConsolas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Hogwarts Legacy',
    'RPG de acción y exploración ambientado en el mundo mágico de Hogwarts.',
    ['RPG', 'Aventura'],
    todas,
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Resident Evil 2',
    'Remake de 2019: supervivencia y terror en Raccoon City.',
    ['Terror', 'Supervivencia'],
    pcConsolas,
    ['Un jugador', 'Historia', 'Exploración', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Resident Evil 4',
    'Remake de 2023: rescate, acción y terror protagonizados por Leon Kennedy.',
    ['Acción', 'Terror', 'Shooter'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Resident Evil Village',
    'Aventura de terror y supervivencia en un pueblo aislado.',
    ['Terror', 'Supervivencia', 'Shooter'],
    pcConsolas,
    ['Un jugador', 'Historia', 'Exploración', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Silent Hill 2',
    'Remake de 2024: terror psicológico y exploración en Silent Hill.',
    ['Terror', 'Aventura'],
    ['PC', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Exploración', 'Terror'],
  ),
  juego(
    'DOOM Eternal',
    'Shooter de acción rápida con gestión de recursos durante el combate.',
    ['Shooter', 'Acción'],
    todas,
    ['Un jugador', 'Multijugador', 'Combate desafiante'],
  ),
  juego(
    'DOOM',
    'Edición de 2016: shooter de acción contra demonios en instalaciones de Marte.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Combate desafiante'],
  ),
  juego(
    'Halo Infinite',
    'Shooter de ciencia ficción con campaña y partidas multijugador competitivas.',
    ['Shooter', 'Acción'],
    ['PC', 'Xbox One', 'Xbox Series'],
    [
      'Mundo abierto',
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Competitivo',
    ],
  ),
  juego(
    'Counter-Strike 2',
    'Shooter táctico competitivo por equipos con objetivos y economía por ronda.',
    ['Shooter'],
    ['PC'],
    ['Multijugador', 'Competitivo'],
  ),
  juego(
    'Valorant',
    'Shooter táctico por equipos que combina precisión y habilidades de agentes.',
    ['Shooter'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Multijugador', 'Competitivo'],
  ),
  juego(
    'Overwatch 2',
    'Shooter por equipos con héroes de distintos roles y objetivos compartidos.',
    ['Shooter', 'Acción'],
    todas,
    ['Multijugador', 'Competitivo'],
  ),
  juego(
    'Apex Legends',
    'Battle royale por escuadrones con personajes y habilidades diferenciadas.',
    ['Shooter', 'Acción'],
    todas,
    ['Multijugador', 'Competitivo'],
  ),
  juego(
    'Fortnite',
    'Battle royale con combate, construcción y modos creativos.',
    ['Shooter', 'Acción'],
    todas,
    ['Multijugador', 'Competitivo', 'Construcción', 'Sandbox'],
  ),
  juego(
    'Minecraft',
    'Sandbox de bloques con construcción, exploración y supervivencia.',
    ['Supervivencia', 'Aventura'],
    todas,
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Construcción',
      'Supervivencia',
      'Sandbox',
    ],
  ),
  juego(
    'Terraria',
    'Sandbox en dos dimensiones con exploración, construcción y combates.',
    ['Indie', 'Supervivencia', 'Aventura'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Construcción',
      'Supervivencia',
      'Sandbox',
    ],
  ),
  juego(
    'Stardew Valley',
    'Simulación de granja con vida comunitaria, cultivo y exploración.',
    ['Indie', 'Simulación', 'RPG'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Cooperativo', 'Gestión', 'Exploración'],
  ),
  juego(
    'Hades',
    'Roguelike de acción sobre intentos de escapar del inframundo griego.',
    ['Indie', 'Acción', 'RPG'],
    todas,
    ['Un jugador', 'Historia', 'Combate desafiante', 'Roguelike'],
  ),
  juego(
    'Hollow Knight',
    'Aventura de exploración y plataformas en un reino subterráneo.',
    ['Indie', 'Acción', 'Plataformas'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Celeste',
    'Plataformas de precisión sobre una escalada y la superación personal.',
    ['Indie', 'Plataformas'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'Cuphead',
    'Acción y plataformas con jefes exigentes y estética de animación clásica.',
    ['Indie', 'Acción', 'Plataformas'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Cooperativo', 'Combate desafiante'],
  ),
  juego(
    'Dead Cells',
    'Roguelike de acción y plataformas con rutas y equipo variables.',
    ['Indie', 'Acción', 'Plataformas'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Exploración', 'Combate desafiante', 'Roguelike'],
  ),
  juego(
    'Civilization VI',
    'Estrategia por turnos para desarrollar una civilización a través de las eras.',
    ['Estrategia'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Gestión', 'Estrategia por turnos'],
  ),
  juego(
    'Age of Empires IV',
    'Estrategia en tiempo real con civilizaciones históricas y gestión de recursos.',
    ['Estrategia'],
    ['PC', 'Xbox One', 'Xbox Series'],
    ['Un jugador', 'Multijugador', 'Competitivo', 'Gestión', 'Construcción'],
  ),
  juego(
    'Cities: Skylines',
    'Simulación de planificación urbana, servicios y transporte.',
    ['Simulación', 'Estrategia'],
    todas,
    ['Un jugador', 'Gestión', 'Construcción', 'Sandbox'],
  ),
  juego(
    'The Sims 4',
    'Simulación de vida con creación de hogares y relaciones entre personajes.',
    ['Simulación'],
    pcAnterior,
    ['Un jugador', 'Gestión', 'Construcción', 'Sandbox'],
  ),
  juego(
    'Forza Horizon 5',
    'Carreras en un mundo abierto inspirado en México.',
    ['Carreras'],
    ['PC', 'PlayStation 5', 'Xbox One', 'Xbox Series'],
    [
      'Mundo abierto',
      'Un jugador',
      'Multijugador',
      'Competitivo',
      'Exploración',
    ],
  ),
  juego(
    'Gran Turismo 7',
    'Carreras con colección de vehículos y competiciones en circuitos.',
    ['Carreras', 'Simulación'],
    ['PlayStation 4', 'PlayStation 5'],
    ['Un jugador', 'Multijugador', 'Competitivo'],
  ),
  juego(
    'EA Sports FC 24',
    'Fútbol con clubes, selecciones y modalidades individuales y competitivas.',
    ['Deportes', 'Simulación'],
    todas,
    ['Un jugador', 'Multijugador', 'Competitivo', 'Gestión'],
  ),
  juego(
    'Rocket League',
    'Partidos de fútbol con vehículos y juego competitivo por equipos.',
    ['Deportes', 'Carreras'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Competitivo'],
  ),
  juego(
    'Portal 2',
    'Aventura de puzles con portales, narrativa y campaña cooperativa.',
    ['Aventura'],
    ['PC'],
    ['Un jugador', 'Cooperativo', 'Historia'],
  ),
  juego(
    'It Takes Two',
    'Aventura diseñada para dos jugadores con mecánicas cooperativas variadas.',
    ['Aventura', 'Plataformas'],
    todas,
    ['Multijugador', 'Cooperativo', 'Historia'],
  ),
  juego(
    'Monster Hunter: World',
    'RPG de acción centrado en cacerías, equipo y cooperación.',
    ['RPG', 'Acción'],
    pcAnterior,
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Combate desafiante',
    ],
  ),
  juego(
    'Death Stranding',
    'Edición original: aventura de entregas y conexión entre comunidades aisladas.',
    ['Aventura', 'Acción'],
    ['PC', 'PlayStation 4'],
    ['Mundo abierto', 'Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    "Marvel's Spider-Man Remastered",
    'Aventura de Peter Parker con balanceo por Nueva York y combate contra sus enemigos. Versión remasterizada.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto'],
  ),
  juego(
    "Marvel's Spider-Man: Miles Morales",
    'Miles aprende a proteger Nueva York con sus propios poderes y un estilo de combate ágil.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto'],
  ),
  juego(
    "Marvel's Spider-Man 2",
    'Peter Parker y Miles Morales comparten una aventura de acción por Nueva York.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto'],
  ),
  juego(
    "Uncharted 4: A Thief's End",
    'Nathan Drake busca un tesoro pirata entre ruinas, tiroteos y secuencias de escalada. Se representa la edición original de PS4.',
    ['Acción', 'Aventura'],
    ['PlayStation 4'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Uncharted: The Lost Legacy',
    'Chloe y Nadine buscan una reliquia en India combinando exploración, escalada y combate. Se representa la edición original de PS4.',
    ['Acción', 'Aventura'],
    ['PlayStation 4'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Resident Evil Requiem',
    'Terror y acción con investigación, recursos limitados y encuentros con criaturas en escenarios hostiles.',
    ['Terror', 'Supervivencia', 'Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Exploración', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Far Cry 2',
    'Shooter en una región africana en conflicto, con desplazamientos libres y misiones para facciones enfrentadas.',
    ['Shooter', 'Acción'],
    ['PC'],
    ['Un jugador', 'Mundo abierto', 'Exploración'],
  ),
  juego(
    'Far Cry 3',
    'Shooter de supervivencia en una isla tropical con campamentos enemigos y exploración libre. Se representa la versión original de PC.',
    ['Shooter', 'Acción'],
    ['PC'],
    ['Un jugador', 'Historia', 'Mundo abierto', 'Exploración'],
  ),
  juego(
    'Far Cry 4',
    'Shooter ambientado en Kyrat, con puestos enemigos y exploración de un territorio montañoso.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    [
      'Un jugador',
      'Historia',
      'Mundo abierto',
      'Exploración',
      'Cooperativo',
      'Multijugador',
    ],
  ),
  juego(
    'Far Cry 5',
    'Shooter de mundo abierto sobre la resistencia contra una secta en una región rural de Estados Unidos.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    [
      'Un jugador',
      'Historia',
      'Mundo abierto',
      'Exploración',
      'Cooperativo',
      'Multijugador',
    ],
  ),
  juego(
    'Far Cry Primal',
    'Aventura prehistórica con caza, armas rudimentarias y dominio de animales en un entorno hostil.',
    ['Acción', 'Aventura', 'Supervivencia'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Historia', 'Mundo abierto', 'Exploración', 'Supervivencia'],
  ),
  juego(
    'Devil May Cry 5',
    'Acción de combate estilizado con tres protagonistas y cadenas de ataques contra demonios. Edición base.',
    ['Acción'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'Ori and the Blind Forest: Definitive Edition',
    'Plataformas y exploración de un bosque con habilidades que permiten abrir nuevos caminos. Edición definitiva.',
    ['Plataformas', 'Aventura', 'Indie'],
    ['PC', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Ori and the Will of the Wisps',
    'Aventura de plataformas con exploración, nuevas habilidades y combates en un mundo natural fantástico.',
    ['Plataformas', 'Aventura', 'Indie'],
    ['PC', 'Xbox One', 'Xbox Series', 'Nintendo Switch'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Final Fantasy VII Remake Intergrade',
    'RPG de acción sobre Cloud y la resistencia en Midgar. Esta edición incluye el episodio protagonizado por Yuffie.',
    ['RPG', 'Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Final Fantasy VII Rebirth',
    'Cloud y sus compañeros recorren regiones abiertas en una aventura de rol con combate de acción y decisiones tácticas.',
    ['RPG', 'Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto'],
  ),
  juego(
    'Final Fantasy XVI',
    'RPG de acción centrado en Clive, conflictos entre reinos y enfrentamientos con poderosas criaturas.',
    ['RPG', 'Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'Mortal Kombat 11',
    'Combates uno contra uno con personajes de estilos distintos, campaña narrativa y duelos competitivos.',
    ['Lucha', 'Acción'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    [
      'Un jugador',
      'Multijugador',
      'Competitivo',
      'Combate desafiante',
      'Historia',
    ],
  ),
  juego(
    'Mortal Kombat 1',
    'Juego de lucha con una nueva etapa de la historia y personajes de apoyo durante los combates.',
    ['Lucha', 'Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series', 'Nintendo Switch'],
    [
      'Un jugador',
      'Multijugador',
      'Competitivo',
      'Combate desafiante',
      'Historia',
    ],
  ),
  juego(
    'The Binding of Isaac: Rebirth',
    'Acción roguelike con mazmorras variables y objetos que modifican los ataques de Isaac.',
    ['Indie', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Cooperativo', 'Roguelike', 'Combate desafiante'],
  ),
  juego(
    'DAVE THE DIVER',
    'Aventura que alterna exploración submarina con la gestión de un restaurante de sushi.',
    ['Aventura', 'Simulación'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Un jugador', 'Exploración', 'Gestión', 'Historia'],
  ),
  juego(
    'Kingdom Hearts III',
    'RPG de acción en el que Sora y sus compañeros recorren mundos de Disney para enfrentarse a la oscuridad.',
    ['RPG', 'Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Until Dawn',
    'Remake de terror narrativo en el que las decisiones alteran el destino de un grupo atrapado en una montaña.',
    ['Terror', 'Aventura'],
    ['PC', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Terror', 'Exploración'],
  ),
  juego(
    'Lies of P',
    'RPG de acción con duelos exigentes y exploración de una ciudad dominada por marionetas.',
    ['RPG', 'Acción'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Undertale',
    'RPG en el que las decisiones durante los encuentros influyen en la relación con los habitantes del subsuelo.',
    ['RPG', 'Indie'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Sifu',
    'Acción de artes marciales con combates cuerpo a cuerpo y un protagonista que envejece al caer.',
    ['Acción', 'Indie'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'NINJA GAIDEN 2 Black',
    'Acción con espadas, movilidad rápida y combates exigentes protagonizados por Ryu Hayabusa.',
    ['Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'NINJA GAIDEN 4',
    'Acción ninja con combates rápidos, técnicas de espada y enfrentamientos en una ciudad futurista.',
    ['Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'Megabonk',
    'Acción roguelike en tres dimensiones con hordas de enemigos y mejoras que cambian cada partida.',
    ['Indie', 'Acción'],
    ['PC'],
    ['Un jugador', 'Roguelike', 'Combate desafiante'],
  ),
  juego(
    "No Man's Sky",
    'Exploración espacial con viajes entre planetas, recolección de recursos y construcción de bases.',
    ['Aventura', 'Supervivencia'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Mundo abierto',
      'Exploración',
      'Supervivencia',
      'Construcción',
      'Sandbox',
    ],
  ),
  juego(
    'Sniper Elite 5',
    'Shooter táctico con infiltración y disparos de precisión en misiones ambientadas en la Segunda Guerra Mundial.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Cooperativo', 'Multijugador', 'Competitivo'],
  ),
  juego(
    'Mortal Shell',
    'RPG de acción con exploración de un mundo oscuro y combate basado en aprender los movimientos del rival. Edición base.',
    ['RPG', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    "Marvel's Wolverine",
    'Aventura de acción narrativa para un jugador, centrada en Logan y combates cuerpo a cuerpo con sus garras.',
    ['Acción', 'Aventura'],
    ['PlayStation 5'],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'Batman: Arkham Asylum',
    'Batman recorre el asilo Arkham combinando investigación, sigilo y combate cuerpo a cuerpo. Se representa la edición de PC.',
    ['Acción', 'Aventura'],
    ['PC'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Batman: Arkham City',
    'Batman investiga una zona de Gotham convertida en prisión, con exploración libre y enfrentamientos con sus villanos. Se representa la edición de PC.',
    ['Acción', 'Aventura'],
    ['PC'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto'],
  ),
  juego(
    'Batman: Arkham Knight',
    'Aventura de Batman en Gotham con sigilo, combate y desplazamientos en el Batmóvil.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto'],
  ),
  juego(
    'BioShock Remastered',
    'Shooter narrativo en la ciudad submarina de Rapture, con armas y poderes que permiten distintas estrategias.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'BioShock Infinite',
    'Shooter narrativo en una ciudad flotante, con poderes y desplazamientos por raíles elevados.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Blasphemous',
    'Acción y plataformas en un mundo religioso oscuro, con exploración conectada y jefes exigentes.',
    ['Acción', 'Plataformas', 'Indie'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Exploración', 'Combate desafiante', 'Historia'],
  ),
  juego(
    'Blasphemous 2',
    'Aventura de acción y plataformas con nuevas armas y habilidades para recorrer escenarios interconectados.',
    ['Acción', 'Plataformas', 'Indie'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Un jugador', 'Exploración', 'Combate desafiante', 'Historia'],
  ),
  juego(
    'Borderlands 2',
    'Shooter de rol con botín, personajes de habilidades distintas y misiones cooperativas en Pandora.',
    ['Shooter', 'RPG'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Cooperativo', 'Historia', 'Exploración'],
  ),
  juego(
    'Borderlands 3',
    'Shooter de rol con abundante equipo y viajes entre planetas para combatir en solitario o en cooperación.',
    ['Shooter', 'RPG'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Un jugador', 'Multijugador', 'Cooperativo', 'Historia', 'Exploración'],
  ),
  juego(
    'Borderlands 4',
    'Shooter de rol con búsqueda de botín, habilidades de personaje y exploración del planeta Kairos.',
    ['Shooter', 'RPG'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Historia',
      'Exploración',
      'Mundo abierto',
    ],
  ),
  juego(
    'Clair Obscur: Expedition 33',
    'RPG con combates por turnos que incorporan acciones en tiempo real y una expedición contra la Pintora.',
    ['RPG'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    [
      'Un jugador',
      'Historia',
      'Exploración',
      'Estrategia por turnos',
      'Combate desafiante',
    ],
  ),
  juego(
    'Crash Bandicoot N. Sane Trilogy',
    'Recopilación de tres aventuras de plataformas reconstruidas, con saltos, obstáculos y recolección de objetos.',
    ['Plataformas', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Combate desafiante'],
  ),
  juego(
    "Crash Bandicoot 4: It's About Time",
    'Plataformas con viajes entre dimensiones y máscaras que alteran las reglas de cada escenario.',
    ['Plataformas', 'Acción'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'Ratchet & Clank: Rift Apart',
    'Aventura de acción y plataformas con armas variadas y saltos entre dimensiones.',
    ['Acción', 'Aventura', 'Plataformas'],
    ['PC', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Diablo II: Resurrected',
    'Remaster del RPG de acción con clases, exploración de mazmorras y búsqueda de equipo.',
    ['RPG', 'Acción'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Exploración',
      'Combate desafiante',
    ],
  ),
  juego(
    'Diablo IV',
    'RPG de acción con clases, mazmorras y búsqueda de botín en un mundo compartido.',
    ['RPG', 'Acción'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series'],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Mundo abierto',
      'Exploración',
      'Combate desafiante',
    ],
  ),
  juego(
    'Detroit: Become Human',
    'Aventura narrativa sobre androides en la que las decisiones abren rutas y desenlaces diferentes.',
    ['Aventura'],
    ['PC', 'PlayStation 4'],
    ['Un jugador', 'Historia'],
  ),
  juego(
    'Left 4 Dead 2',
    'Shooter cooperativo en el que un grupo intenta sobrevivir a hordas de infectados durante distintas campañas.',
    ['Shooter', 'Supervivencia', 'Terror'],
    ['PC'],
    ['Un jugador', 'Multijugador', 'Cooperativo', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Little Nightmares',
    'Aventura de terror y plataformas sobre una niña que intenta escapar de un lugar habitado por seres amenazantes.',
    ['Terror', 'Aventura', 'Plataformas'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Historia', 'Exploración', 'Terror'],
  ),
  juego(
    'Little Nightmares II',
    'Aventura de terror y plataformas con dos niños que atraviesan escenarios distorsionados y peligrosos.',
    ['Terror', 'Aventura', 'Plataformas'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Un jugador', 'Historia', 'Exploración', 'Terror'],
  ),
  juego(
    'Little Nightmares III',
    'Aventura de terror en la que dos niños colaboran para escapar, en solitario con un acompañante controlado por el juego o en cooperativo en línea.',
    ['Terror', 'Aventura', 'Plataformas'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Historia',
      'Exploración',
      'Terror',
    ],
  ),
  juego(
    'Metal Gear Rising: Revengeance',
    'Acción con espada protagonizada por Raiden, centrada en duelos rápidos y cortes precisos.',
    ['Acción'],
    ['PC'],
    ['Un jugador', 'Historia', 'Combate desafiante'],
  ),
  juego(
    'Middle-earth: Shadow of Mordor',
    'Acción y exploración en Mordor con sigilo y enfrentamientos contra capitanes orcos.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto'],
  ),
  juego(
    'Middle-earth: Shadow of War',
    'Aventura de acción en la que se recluta un ejército y se disputan fortalezas en Mordor.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto'],
  ),
  juego(
    'Star Wars Jedi: Fallen Order',
    'Aventura de Cal Kestis con combate de sable, poderes de la Fuerza y exploración de planetas.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Star Wars Jedi: Survivor',
    'Cal continúa su aventura con nuevas posturas de combate y regiones que se abren mediante habilidades.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Street Fighter 6',
    'Juego de lucha con duelos competitivos y un modo de aventura para desarrollar un luchador propio.',
    ['Lucha', 'Acción'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Multijugador', 'Competitivo', 'Combate desafiante'],
  ),
  juego(
    'ULTRAKILL',
    'Shooter de acción rápida con movimiento constante, combinaciones de armas y puntuación por estilo.',
    ['Shooter', 'Acción', 'Indie'],
    ['PC'],
    ['Un jugador', 'Combate desafiante'],
  ),
  juego(
    'Tomb Raider (2013)',
    'Aventura de supervivencia de Lara Croft en una isla, con exploración, escalada y combate. Edición original de 2013.',
    ['Acción', 'Aventura'],
    ['PC'],
    ['Un jugador', 'Historia', 'Exploración', 'Supervivencia'],
  ),
  juego(
    'Rise of the Tomb Raider',
    'Lara busca una ciudad perdida combinando exploración de tumbas, escalada y combate.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Historia', 'Exploración', 'Supervivencia'],
  ),
  juego(
    'Shadow of the Tomb Raider',
    'Lara explora selvas y tumbas mientras intenta detener una catástrofe vinculada a una civilización antigua.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    "Tom Clancy's Ghost Recon Wildlands",
    'Shooter táctico en un territorio abierto con misiones de infiltración y cooperación entre soldados.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Historia',
      'Mundo abierto',
      'Exploración',
    ],
  ),
  juego(
    "Tom Clancy's Ghost Recon Breakpoint",
    'Shooter táctico con infiltración, equipo y misiones en una isla controlada por fuerzas hostiles.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Historia',
      'Mundo abierto',
      'Exploración',
    ],
  ),
  juego(
    'The Last of Us Part I',
    'Remake de una aventura de supervivencia narrativa con sigilo, recursos limitados y enfrentamientos con infectados.',
    ['Acción', 'Aventura', 'Supervivencia'],
    ['PC', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Supervivencia', 'Terror'],
  ),
  juego(
    'The Last of Us Part II Remastered',
    'Edición remasterizada de una aventura de supervivencia que combina sigilo, combate y una historia de venganza.',
    ['Acción', 'Aventura', 'Supervivencia'],
    ['PC', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Grand Theft Auto IV',
    'Niko Bellic recorre Liberty City en una aventura de crimen, conducción y misiones de mundo abierto.',
    ['Acción', 'Aventura'],
    ['PC'],
    ['Un jugador', 'Historia', 'Mundo abierto', 'Exploración', 'Sandbox'],
  ),
  juego(
    'Dead by Daylight',
    'Terror multijugador asimétrico en el que supervivientes intentan escapar de un asesino.',
    ['Terror', 'Supervivencia'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Multijugador', 'Cooperativo', 'Competitivo', 'Supervivencia', 'Terror'],
  ),
  juego(
    'Marvel Rivals',
    'Shooter competitivo por equipos con héroes de Marvel y habilidades que pueden combinarse.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox Series'],
    ['Multijugador', 'Competitivo'],
  ),
  juego(
    'Battlefield 1',
    'Shooter ambientado en la Primera Guerra Mundial, con historias individuales y batallas multijugador a gran escala.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Multijugador', 'Competitivo', 'Historia'],
  ),
  juego(
    'Battlefield 6',
    'Shooter militar con campaña y combates multijugador que combinan infantería, vehículos y destrucción.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Multijugador', 'Competitivo', 'Historia'],
  ),
  juego(
    'Call of Duty: Modern Warfare (2019)',
    'Shooter militar con campaña narrativa, partidas competitivas y operaciones cooperativas. Entrega de 2019.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Multijugador', 'Cooperativo', 'Competitivo', 'Historia'],
  ),
  juego(
    'Call of Duty: Black Ops 6',
    'Shooter con campaña de espionaje, multijugador competitivo y supervivencia cooperativa contra zombis.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series'],
    ['Un jugador', 'Multijugador', 'Cooperativo', 'Competitivo', 'Historia'],
  ),
  juego(
    'ARK: Survival Ascended',
    'Supervivencia con dinosaurios, recolección de recursos y construcción de bases en escenarios abiertos.',
    ['Supervivencia', 'Aventura'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    [
      'Un jugador',
      'Multijugador',
      'Cooperativo',
      'Mundo abierto',
      'Exploración',
      'Supervivencia',
      'Construcción',
      'Sandbox',
    ],
  ),
  juego(
    'Split Fiction',
    'Aventura diseñada para dos jugadores que alterna mundos de fantasía y ciencia ficción con desafíos cooperativos.',
    ['Acción', 'Aventura', 'Plataformas'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Multijugador', 'Cooperativo', 'Historia', 'Exploración'],
  ),
  juego(
    'Subnautica',
    'Supervivencia submarina con exploración, fabricación y construcción de bases en un planeta oceánico.',
    ['Aventura', 'Supervivencia'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    [
      'Un jugador',
      'Exploración',
      'Supervivencia',
      'Construcción',
      'Mundo abierto',
    ],
  ),
  juego(
    'Subnautica: Below Zero',
    'Aventura de supervivencia en una región helada, con exploración submarina y construcción de refugios.',
    ['Aventura', 'Supervivencia'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    [
      'Un jugador',
      'Historia',
      'Exploración',
      'Supervivencia',
      'Construcción',
      'Mundo abierto',
    ],
  ),
  juego(
    'Black Myth: Wukong',
    'RPG de acción inspirado en la mitología china, con exploración y duelos contra criaturas legendarias.',
    ['RPG', 'Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'World War Z: Aftermath',
    'Shooter cooperativo contra hordas de zombis, con campañas y clases de supervivientes.',
    ['Shooter', 'Acción', 'Supervivencia'],
    ['PC', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series'],
    ['Un jugador', 'Multijugador', 'Cooperativo', 'Supervivencia'],
  ),
  juego(
    'Stray',
    'Aventura de un gato que explora una ciudad habitada por robots y busca una salida.',
    ['Aventura', 'Indie'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Tekken 8',
    'Lucha en tres dimensiones con personajes de estilos distintos y duelos centrados en la presión ofensiva.',
    ['Lucha', 'Acción'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    [
      'Un jugador',
      'Multijugador',
      'Competitivo',
      'Combate desafiante',
      'Historia',
    ],
  ),
  juego(
    'PAYDAY 2',
    'Shooter cooperativo de atracos con preparación de equipo y misiones que permiten sigilo o enfrentamientos abiertos.',
    ['Shooter', 'Acción'],
    ['PC', 'PlayStation 4', 'Xbox One', 'Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Cooperativo'],
  ),
  juego(
    'Metal Gear Solid V: The Phantom Pain',
    'Acción táctica y sigilo con misiones abiertas, extracción de recursos y desarrollo de una base.',
    ['Acción', 'Aventura'],
    ['PC', 'PlayStation 4', 'Xbox One'],
    ['Un jugador', 'Historia', 'Mundo abierto', 'Exploración', 'Gestión'],
  ),
  juego(
    'Metal Gear Solid Delta: Snake Eater',
    'Remake de una aventura de espionaje y supervivencia en la selva, centrada en infiltración y sigilo.',
    ['Acción', 'Aventura', 'Supervivencia'],
    ['PC', 'PlayStation 5', 'Xbox Series'],
    ['Un jugador', 'Historia', 'Exploración', 'Supervivencia'],
  ),
  juego(
    'Guilty Gear -Strive-',
    'Juego de lucha con personajes de mecánicas diferenciadas y combates competitivos de ritmo rápido.',
    ['Lucha', 'Acción'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Un jugador', 'Multijugador', 'Competitivo', 'Combate desafiante'],
  ),
  juego(
    'YAPYAP',
    'Terror cooperativo con magia activada por voz para causar destrozos y evadir amenazas en una torre.',
    ['Terror', 'Acción', 'Indie'],
    ['PC'],
    ['Multijugador', 'Cooperativo', 'Terror'],
  ),
  juego(
    'Disco Elysium - The Final Cut',
    'RPG de investigación en el que diálogos, habilidades y decisiones definen cómo se resuelve un caso. Edición The Final Cut.',
    ['RPG', 'Aventura'],
    [
      'PC',
      'PlayStation 4',
      'PlayStation 5',
      'Xbox One',
      'Xbox Series',
      'Nintendo Switch',
    ],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
  juego(
    'Halo: The Master Chief Collection',
    'Recopilación de campañas y modos multijugador de Halo, con combates de ciencia ficción y cooperación.',
    ['Shooter', 'Acción'],
    ['PC', 'Xbox One', 'Xbox Series'],
    ['Un jugador', 'Multijugador', 'Cooperativo', 'Competitivo', 'Historia'],
  ),
  juego(
    'The Legend of Zelda: Breath of the Wild',
    'Aventura de exploración libre en Hyrule con santuarios, escalada y sistemas que permiten resolver desafíos de distintas formas.',
    ['Acción', 'Aventura'],
    ['Nintendo Switch'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto'],
  ),
  juego(
    'The Legend of Zelda: Tears of the Kingdom',
    'Aventura en Hyrule con exploración de cielos y profundidades, y habilidades para construir y combinar objetos.',
    ['Acción', 'Aventura'],
    ['Nintendo Switch'],
    ['Un jugador', 'Historia', 'Exploración', 'Mundo abierto', 'Construcción'],
  ),
  juego(
    'Super Mario Party Jamboree',
    'Juego de tableros y minijuegos con personajes de Mario, desafíos individuales y partidas compartidas.',
    ['Aventura'],
    ['Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Cooperativo', 'Competitivo'],
  ),
  juego(
    'Super Mario Bros. Wonder',
    'Plataformas en dos dimensiones con efectos que transforman los niveles y juego compartido.',
    ['Plataformas'],
    ['Nintendo Switch'],
    ['Un jugador', 'Multijugador', 'Cooperativo', 'Exploración'],
  ),
  juego(
    'Super Mario Odyssey',
    'Aventura de plataformas en tres dimensiones donde Mario explora reinos y utiliza a Cappy para adoptar nuevas habilidades.',
    ['Plataformas', 'Aventura'],
    ['Nintendo Switch'],
    ['Un jugador', 'Cooperativo', 'Exploración'],
  ),
  juego(
    'Shadow of the Colossus (2018)',
    'Remake de la aventura de Wander, centrada en explorar un territorio solitario y encontrar cómo derrotar a gigantes.',
    ['Acción', 'Aventura'],
    ['PlayStation 4'],
    ['Un jugador', 'Historia', 'Exploración', 'Combate desafiante'],
  ),
  juego(
    'Jak and Daxter: The Precursor Legacy',
    'Aventura de plataformas con exploración de escenarios conectados y recolección de objetos. Publicaciones del clásico para PS4 y PS5.',
    ['Plataformas', 'Aventura'],
    ['PlayStation 4', 'PlayStation 5'],
    ['Un jugador', 'Historia', 'Exploración'],
  ),
];
